services:
  postgres:
    image: postgres:latest
    container_name: feriadosDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: feriadosDB
    ports:
      - "5432:5432"